# Generated by Django 4.2.7 on 2026-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='guest_avatars/'),
        ),
    ]
