# Generated by Django 5.2.5 on 2026-07-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_reservation_task_inquiry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guest',
            new_name='properties__last_na_42fdd4_idx',
            old_name='properties_guest_name_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__name_47b1ec_idx',
            old_name='properties_property_name_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='properties__propert_eb4f5b_idx',
            old_name='properties_reservation_prop_checkin_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='properties__propert_14cf8c_idx',
            old_name='properties_reservation_prop_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='properties__propert_f43710_idx',
            old_name='properties_task_prop_status_idx',
        ),
    ]
